-- VOLT Power & Utilities - SPCS Access Grants
-- Run this script to grant access to the deployed service

USE ROLE ACCOUNTADMIN;

-- Create role for app access
CREATE ROLE IF NOT EXISTS VOLT_APP_ROLE;

-- Grant database access
GRANT USAGE ON DATABASE POWER_UTILITIES_DB TO ROLE VOLT_APP_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE POWER_UTILITIES_DB TO ROLE VOLT_APP_ROLE;
GRANT SELECT ON ALL TABLES IN DATABASE POWER_UTILITIES_DB TO ROLE VOLT_APP_ROLE;
GRANT SELECT ON ALL VIEWS IN DATABASE POWER_UTILITIES_DB TO ROLE VOLT_APP_ROLE;

-- Grant Yes Energy data access
GRANT USAGE ON DATABASE YES_ENERGY_FOUNDATION_DATA TO ROLE VOLT_APP_ROLE;
GRANT USAGE ON SCHEMA YES_ENERGY_FOUNDATION_DATA.FOUNDATION TO ROLE VOLT_APP_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA YES_ENERGY_FOUNDATION_DATA.FOUNDATION TO ROLE VOLT_APP_ROLE;

-- Grant warehouse access
GRANT USAGE ON WAREHOUSE POWER_UTILITIES_WH TO ROLE VOLT_APP_ROLE;

-- Grant Cortex Search service access
GRANT USAGE ON CORTEX SEARCH SERVICE POWER_UTILITIES_DB.DOCS.RTO_NEWS_SEARCH TO ROLE VOLT_APP_ROLE;
GRANT USAGE ON CORTEX SEARCH SERVICE POWER_UTILITIES_DB.DOCS.ERCOT_RULES_SEARCH TO ROLE VOLT_APP_ROLE;

-- Grant future tables
GRANT SELECT ON FUTURE TABLES IN DATABASE POWER_UTILITIES_DB TO ROLE VOLT_APP_ROLE;

-- Grant service endpoint access
-- GRANT USAGE ON SERVICE POWER_UTILITIES_DB.SPCS.VOLT_SERVICE TO ROLE VOLT_APP_ROLE;

SHOW GRANTS TO ROLE VOLT_APP_ROLE;
