-- ============================================================================
-- POWER & UTILITIES INTELLIGENCE PLATFORM - Atomic Tables
-- ============================================================================
-- Core entity tables pulling from YES_ENERGY_FOUNDATION_DATA
-- ============================================================================

USE DATABASE POWER_UTILITIES_DB;
USE SCHEMA ATOMIC;

-- ============================================================================
-- REFERENCE TABLES
-- ============================================================================

-- ERCOT Load Zones (Houston, North, South, West)
CREATE OR REPLACE TABLE LOAD_ZONE (
    ZONE_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    ZONE_CODE VARCHAR(50) NOT NULL,
    ZONE_NAME VARCHAR(100) NOT NULL,
    ZONE_TYPE VARCHAR(50),
    ISO VARCHAR(20) DEFAULT 'ERCOT',
    LATITUDE FLOAT,
    LONGITUDE FLOAT,
    POPULATION_SERVED NUMBER,
    PEAK_LOAD_MW NUMBER,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Seed ERCOT zones
INSERT INTO LOAD_ZONE (ZONE_CODE, ZONE_NAME, ZONE_TYPE, LATITUDE, LONGITUDE, POPULATION_SERVED, PEAK_LOAD_MW)
VALUES 
    ('HOUSTON', 'Houston Zone', 'LOAD_ZONE', 29.7604, -95.3698, 7000000, 22000),
    ('NORTH', 'North Zone', 'LOAD_ZONE', 32.7767, -96.7970, 8000000, 25000),
    ('SOUTH', 'South Zone', 'LOAD_ZONE', 29.4241, -98.4936, 3500000, 12000),
    ('WEST', 'West Zone', 'LOAD_ZONE', 31.9686, -99.9018, 1500000, 8000);

-- Price Nodes
CREATE OR REPLACE TABLE PRICE_NODE (
    NODE_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    YES_ENERGY_OBJECT_ID NUMBER,
    NODE_NAME VARCHAR(100) NOT NULL,
    ZONE_CODE VARCHAR(50),
    NODE_TYPE VARCHAR(50),
    ISO VARCHAR(20) DEFAULT 'ERCOT',
    FIRST_PRICE_DATE TIMESTAMP_NTZ,
    LAST_PRICE_DATE TIMESTAMP_NTZ,
    STATUS VARCHAR(20) DEFAULT 'Active',
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Weather Stations
CREATE OR REPLACE TABLE WEATHER_STATION (
    STATION_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    YES_ENERGY_OBJECT_ID NUMBER,
    STATION_NAME VARCHAR(100),
    WBAN_CODE VARCHAR(20),
    ZONE_CODE VARCHAR(50),
    LATITUDE FLOAT,
    LONGITUDE FLOAT,
    ELEVATION_FT NUMBER,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Generation Units
CREATE OR REPLACE TABLE GENERATION_UNIT (
    UNIT_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    YES_ENERGY_OBJECT_ID NUMBER,
    UNIT_NAME VARCHAR(100) NOT NULL,
    PLANT_NAME VARCHAR(100),
    ZONE_CODE VARCHAR(50),
    FUEL_TYPE VARCHAR(50),
    CAPACITY_MW NUMBER,
    MIN_CAPACITY_MW NUMBER,
    RAMP_RATE_MW_MIN NUMBER,
    HEAT_RATE_BTU_KWH NUMBER,
    ONLINE_DATE DATE,
    STATUS VARCHAR(20) DEFAULT 'Active',
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================================
-- TIME SERIES TABLES
-- ============================================================================

-- Hourly Load Data by Zone
CREATE OR REPLACE TABLE HOURLY_LOAD (
    LOAD_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    ZONE_CODE VARCHAR(50) NOT NULL,
    DATETIME_UTC TIMESTAMP_NTZ NOT NULL,
    DATETIME_LOCAL TIMESTAMP_NTZ,
    LOAD_MW NUMBER(12,2) NOT NULL,
    LOAD_FORECAST_MW NUMBER(12,2),
    FORECAST_ERROR_MW NUMBER(12,2),
    FORECAST_ERROR_PCT NUMBER(8,4),
    DATA_SOURCE VARCHAR(50) DEFAULT 'YES_ENERGY',
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT UK_HOURLY_LOAD UNIQUE (ZONE_CODE, DATETIME_UTC)
);

-- LMP Prices by Zone/Node
CREATE OR REPLACE TABLE HOURLY_LMP (
    LMP_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    NODE_NAME VARCHAR(100) NOT NULL,
    ZONE_CODE VARCHAR(50),
    DATETIME_UTC TIMESTAMP_NTZ NOT NULL,
    DATETIME_LOCAL TIMESTAMP_NTZ,
    DA_LMP NUMBER(12,4),
    DA_CONGESTION NUMBER(12,4),
    DA_LOSS NUMBER(12,4),
    RT_LMP NUMBER(12,4),
    RT_CONGESTION NUMBER(12,4),
    RT_LOSS NUMBER(12,4),
    DA_RT_SPREAD NUMBER(12,4),
    IS_PRICE_SPIKE BOOLEAN DEFAULT FALSE,
    DATA_SOURCE VARCHAR(50) DEFAULT 'YES_ENERGY',
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT UK_HOURLY_LMP UNIQUE (NODE_NAME, DATETIME_UTC)
);

-- Weather Observations
CREATE OR REPLACE TABLE HOURLY_WEATHER (
    WEATHER_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    STATION_ID NUMBER,
    ZONE_CODE VARCHAR(50),
    DATETIME_UTC TIMESTAMP_NTZ NOT NULL,
    DATETIME_LOCAL TIMESTAMP_NTZ,
    TEMP_F NUMBER(8,2),
    TEMP_FEELS_LIKE_F NUMBER(8,2),
    DEW_POINT_F NUMBER(8,2),
    HUMIDITY_PCT NUMBER(8,2),
    WIND_SPEED_MPH NUMBER(8,2),
    WIND_GUST_MPH NUMBER(8,2),
    WIND_DIRECTION_DEG NUMBER(8,2),
    PRECIP_IN NUMBER(8,4),
    PRESSURE_IN NUMBER(8,4),
    CLOUD_COVER_PCT NUMBER(8,2),
    VISIBILITY_MI NUMBER(8,2),
    CDD NUMBER(8,2),
    HDD NUMBER(8,2),
    WIND_CHILL_F NUMBER(8,2),
    HEAT_INDEX_F NUMBER(8,2),
    IS_EXTREME_WEATHER BOOLEAN DEFAULT FALSE,
    DATA_SOURCE VARCHAR(50) DEFAULT 'YES_ENERGY',
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT UK_HOURLY_WEATHER UNIQUE (ZONE_CODE, DATETIME_UTC)
);

-- Fuel Prices (Daily)
CREATE OR REPLACE TABLE DAILY_FUEL_PRICE (
    FUEL_PRICE_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    PRICE_DATE DATE NOT NULL,
    NG_HENRY_HUB NUMBER(10,4),
    NG_HOUSTON_SHIP NUMBER(10,4),
    NG_WAHA NUMBER(10,4),
    COAL_PRB NUMBER(10,4),
    OIL_WTI NUMBER(10,4),
    CO2_PRICE NUMBER(10,4),
    LNG_PRICE NUMBER(10,4),
    DATA_SOURCE VARCHAR(50) DEFAULT 'YES_ENERGY',
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT UK_DAILY_FUEL_PRICE UNIQUE (PRICE_DATE)
);

-- Generation Output
CREATE OR REPLACE TABLE HOURLY_GENERATION (
    GEN_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    UNIT_ID NUMBER,
    UNIT_NAME VARCHAR(100),
    ZONE_CODE VARCHAR(50),
    DATETIME_UTC TIMESTAMP_NTZ NOT NULL,
    OUTPUT_MW NUMBER(12,2),
    CAPACITY_MW NUMBER(12,2),
    CAPACITY_FACTOR NUMBER(8,4),
    FUEL_TYPE VARCHAR(50),
    DATA_SOURCE VARCHAR(50) DEFAULT 'YES_ENERGY',
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================================
-- EVENT TABLES
-- ============================================================================

-- Price Anomaly Events (detected spikes/drops)
CREATE OR REPLACE TABLE PRICE_ANOMALY_EVENT (
    EVENT_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    EVENT_TYPE VARCHAR(50) NOT NULL,
    ZONE_CODE VARCHAR(50),
    NODE_NAME VARCHAR(100),
    EVENT_START TIMESTAMP_NTZ NOT NULL,
    EVENT_END TIMESTAMP_NTZ,
    DURATION_HOURS NUMBER(8,2),
    PEAK_PRICE NUMBER(12,4),
    AVG_PRICE NUMBER(12,4),
    PRICE_DEVIATION_PCT NUMBER(8,2),
    CONGESTION_COMPONENT NUMBER(12,4),
    PROBABLE_CAUSE VARCHAR(500),
    WEATHER_FACTOR BOOLEAN DEFAULT FALSE,
    OUTAGE_FACTOR BOOLEAN DEFAULT FALSE,
    DEMAND_FACTOR BOOLEAN DEFAULT FALSE,
    SEVERITY VARCHAR(20),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Grid Events (outages, constraints)
CREATE OR REPLACE TABLE GRID_EVENT (
    EVENT_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    EVENT_TYPE VARCHAR(50) NOT NULL,
    EVENT_NAME VARCHAR(200),
    ZONE_CODE VARCHAR(50),
    EVENT_START TIMESTAMP_NTZ NOT NULL,
    EVENT_END TIMESTAMP_NTZ,
    AFFECTED_MW NUMBER(12,2),
    CAUSE_CATEGORY VARCHAR(100),
    DESCRIPTION VARCHAR(2000),
    SEVERITY VARCHAR(20),
    DATA_SOURCE VARCHAR(50),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Congestion Revenue Rights (CRR)
CREATE OR REPLACE TABLE CRR_POSITION (
    CRR_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    SOURCE_ZONE VARCHAR(50) NOT NULL,
    SINK_ZONE VARCHAR(50) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRATION_DATE DATE,
    MW_QUANTITY NUMBER(12,2),
    AUCTION_PRICE NUMBER(12,4),
    SETTLEMENT_PRICE NUMBER(12,4),
    PNL NUMBER(12,4),
    HEDGE_EFFECTIVENESS NUMBER(8,4),
    STATUS VARCHAR(20) DEFAULT 'Active',
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================================
-- INDEXES (Clustering Keys for Performance)
-- ============================================================================

ALTER TABLE HOURLY_LOAD CLUSTER BY (ZONE_CODE, DATETIME_UTC);
ALTER TABLE HOURLY_LMP CLUSTER BY (ZONE_CODE, DATETIME_UTC);
ALTER TABLE HOURLY_WEATHER CLUSTER BY (ZONE_CODE, DATETIME_UTC);
ALTER TABLE PRICE_ANOMALY_EVENT CLUSTER BY (ZONE_CODE, EVENT_START);
